### ISSUE TITLE
highlight="all" applying 'hljs' class on the container instead of the code elements

### ISSUE THREAD

**Issue by h4k1m0u** [MurhafSousli/ngx-highlightjs#23]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Linux archlinux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

### Versions
Angular CLI: 1.5.0
Node: 9.2.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

### Repro steps
```html
<div highlight="pre code" innerHtml="{{ article.text }}"></div>
```

Below is an example of a text to highlight:

```html
<pre>
<code class="language-javascript">var s2 = ee.ImageCollection('COPERNICUS/S2');</code></pre>
```

### Mention any other details that might be useful
Both `highlight="all"` and `highlight="pre code"` when applied on the parent of the code to highlight (i.e. on the div) tend to apply the style on the whole div instead of applying it on each individual `pre > code`. In fact using the code above I got the whole div with a `background: #f8f8f8`.
Is this the normal behaviour to expect?

Another problem I've observed is that only the first occurence of `pre>code` was being attributed the classes `hljs-*`, and was therefore the only one to be syntax-highlighted.

Thanks.

**Comment by MurhafSousli** [comment]
Hi @h4k1m0u Thanks for reporting. it is fixed in **v1.4.1** here is [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-all?file=app%2Fhome%2Fhome.component.html)

**Comment by h4k1m0u** [comment]
Thanks very much @MurhafSousli for fixing the problem with the class being attributed to the parent instead of the `pre > code` element in **v1.4.1.**

But for me there is still an issue when there are multiple elements, as only the first of them is being syntax highlighted (i.e. affected the hljs class). The difference between my code and [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-all?file=app%2Fhome%2Fhome.component.html) is that for me the html content is being downloaded from a remote location using `this.http.get().subscribe()`.
Although I'm not sure it's because of this that the problem persists.

**Comment by MurhafSousli** [comment]
@h4k1m0u No, there is no difference, it should be the same. can you paste the HTML output of `<div highlight="pre code" innerHtml="{{ article.text }}"></div>`?

Or try to fetch the same data in the [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-all?file=app%2Fhome%2Fhome.component.html)?

**Comment by h4k1m0u** [comment]
I couldn't make the http.get work on stackblitz. However when I add the content of `article.text` above in a variable as you did it's working correctly on [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-all-nrvhsl?file=app%2Fhome%2Fhome.component.ts) (Weird).

**Comment by h4k1m0u** [comment]
I ended up using [mockable.io](https://demo7372622.mockable.io/) because it allows to have an https server api.

Anyway regarding the error I mentioned above, I suspect it was because I'm using `Resolve` because in another project where the data is retrieved normally (with `HttpClient` but without `Resolve`), I don't have the issue of only the first code that's highlighted (Same thing with [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-all-nrvhsl?file=app%2Fhome%2Fhome.component.ts)).

**Comment by h4k1m0u** [comment]
Hi @MurhafSousli, just to let you know (and future visitors) that I've fixed the problem I had above by using the `highlightjs` provided by cdnjs (As stated on the [highlightjs webiste](https://highlightjs.org/download/)), instead of picking only custom package for the languages I was using.

**Comment by jayshah19949596** [comment]
Hi @MurhafSousli ... I am trying to highlight content coming from the server... but unable to highlight the content coming from the server.... it's similar to what @h4k1m0u  did... Is there any fix?

**Comment by MurhafSousli** [comment]
@jayshah19949596 Yes, ofcourse. it should work with the directive `[highlight]="someCode"`, but if for some reason didn't work, use `HighlightJS` service and its function to highlight the code
